CREATE TABLE players (
  username VARCHAR(255) PRIMARY KEY NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL ,
  email VARCHAR(255) NOT NULL,
  paid BOOLEAN DEFAULT FALSE,
  created TIMESTAMP NOT NULL
);